---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bonvast9/acs.bonvastours.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R font-awesome-4.7.0 $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
